### ISSUE TITLE
RustCrypto KMAC

### ISSUE THREAD

**Issue by siv2r** [ok-ryoko/fraczal#1]
I noticed your issue regarding implementing the KMAC algorithm in [RustCrypto/MACs](https://github.com/RustCrypto/MACs/). Are you still working on that project? I am also interested in implementing it and am happy to help however possible.

Sorry for reaching out like this. Unfortunately, I wasn't able to find your contact information.

**Comment by ok-ryoko** [comment]
I’m not currently working on that code; feel free to take a try. If you’re not sure where to start, I recommend attempting an implementation based on fixed-output traits, i.e., `FixedOutput`, as my existing implementation focuses solely on extendable output. This would give the RustCrypto maintainers orthogonal information about what is possible with existing traits.

I updated my profile to indicate how to find my contact information—thank you for pointing out that inconvenience.

**Comment by siv2r** [comment]
Thanks for the advice. I'll take a shot at it.
